version: '3.8'

services:
  service1:
    build:
      context: ./service_1
    container_name: service1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  service2:
    build:
      context: ./service_2
    container_name: service2
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy